-- CreateTable
CREATE TABLE "MOV_TENANT" (
    "TEN_ID" TEXT NOT NULL PRIMARY KEY,
    "TEN_NAME" TEXT NOT NULL,
    "TEN_CODE" TEXT,
    "TEN_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TEN_UPDATED_AT" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "MOV_MEMBER" (
    "MEM_ID" TEXT NOT NULL PRIMARY KEY,
    "MEM_TENANT_ID" TEXT NOT NULL,
    "MEM_EMAIL" TEXT NOT NULL,
    "MEM_PASSWORD_HASH" TEXT,
    "MEM_NAME" TEXT,
    "MEM_GOOGLE_ID" TEXT,
    "MEM_AVATAR_URL" TEXT,
    "MEM_ROLE" TEXT NOT NULL DEFAULT 'MEMBER',
    "MEM_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MEM_UPDATED_AT" DATETIME NOT NULL,
    "MEM_PHONE_NUMBER" TEXT,
    "MEM_DATE_OF_BIRTH" TEXT,
    "MEM_GENDER" TEXT,
    "MEM_PROFILE_PHOTO" TEXT,
    "MEM_TRAINER_CODE" TEXT,
    "MEM_TRAINER_TYPE" TEXT,
    "MEM_OWNER_PROFILE" JSONB,
    "MEM_TRAINER_PROFILE" JSONB,
    "MEM_CLIENT_PROFILE" JSONB,
    "MEM_STAFF_PROFILE" JSONB,
    "MEM_REFRESH_TOKEN" TEXT,
    "MEM_PROFILE_COMPLETED" BOOLEAN NOT NULL DEFAULT false,
    "MEM_ONBOARDING_STEP" INTEGER,
    CONSTRAINT "MOV_MEMBER_MEM_TENANT_ID_fkey" FOREIGN KEY ("MEM_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "MOV_LOCATION" (
    "LOC_ID" TEXT NOT NULL PRIMARY KEY,
    "LOC_TENANT_ID" TEXT NOT NULL,
    "LOC_NAME" TEXT NOT NULL,
    "LOC_ADDRESS" TEXT,
    "LOC_STREET_NUMBER" TEXT,
    "LOC_STREET_NAME" TEXT,
    "LOC_CITY" TEXT,
    "LOC_COUNTY" TEXT,
    "LOC_PROVINCE" TEXT,
    "LOC_POSTAL_CODE" TEXT,
    "LOC_COUNTRY" TEXT,
    "LOC_LATITUDE" REAL,
    "LOC_LONGITUDE" REAL,
    "LOC_ELEVATION" REAL,
    "LOC_CAPACITY" INTEGER,
    "LOC_TYPE" TEXT NOT NULL DEFAULT 'indoor',
    "LOC_TIMEZONE" TEXT NOT NULL DEFAULT 'UTC',
    "LOC_REQUIRES_WEATHER" BOOLEAN NOT NULL DEFAULT false,
    "LOC_WEATHER_ALERT" BOOLEAN NOT NULL DEFAULT false,
    "LOC_CORPORATE_ID" TEXT,
    "LOC_BUILDING_NAME" TEXT,
    "LOC_FLOOR" TEXT,
    "LOC_ROOM_NUMBER" TEXT,
    "LOC_ACCESS_INSTRUCTIONS" TEXT,
    "LOC_AMENITIES" TEXT,
    "LOC_EQUIPMENT" TEXT,
    "LOC_SERVICES" TEXT,
    "LOC_DESCRIPTION" TEXT,
    "LOC_PHOTOS" TEXT,
    "LOC_OPERATING_HOURS" TEXT,
    "LOC_IS_ACTIVE" BOOLEAN NOT NULL DEFAULT true,
    "LOC_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "LOC_UPDATED_AT" DATETIME NOT NULL,
    CONSTRAINT "MOV_LOCATION_LOC_TENANT_ID_fkey" FOREIGN KEY ("LOC_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "MOV_SESSION_TYPE" (
    "STY_ID" TEXT NOT NULL PRIMARY KEY,
    "STY_TENANT_ID" TEXT NOT NULL,
    "STY_NAME" TEXT NOT NULL,
    "STY_DESCRIPTION" TEXT,
    "STY_DURATION_MIN" INTEGER NOT NULL,
    "STY_CATEGORY" TEXT NOT NULL,
    "STY_MAX_CAPACITY" INTEGER,
    "STY_DIFFICULTY" TEXT NOT NULL DEFAULT 'intermediate',
    "STY_IS_OUTDOOR" BOOLEAN NOT NULL DEFAULT false,
    "STY_REQUIRES_WEATHER" BOOLEAN NOT NULL DEFAULT false,
    "STY_WEATHER_CONDITIONS" TEXT,
    "STY_TEMP_MIN" REAL,
    "STY_TEMP_MAX" REAL,
    "STY_EQUIPMENT" TEXT,
    "STY_FITNESS_LEVEL" TEXT,
    "STY_CORPORATE_APPROVED" BOOLEAN NOT NULL DEFAULT true,
    "STY_CREDIT_POINTS" INTEGER,
    "STY_IS_ACTIVE" BOOLEAN NOT NULL DEFAULT true,
    "STY_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "STY_UPDATED_AT" DATETIME NOT NULL,
    CONSTRAINT "MOV_SESSION_TYPE_STY_TENANT_ID_fkey" FOREIGN KEY ("STY_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "MOV_SESSION_INSTANCE" (
    "SIN_ID" TEXT NOT NULL PRIMARY KEY,
    "SIN_TENANT_ID" TEXT NOT NULL,
    "SIN_SESSION_TYPE_ID" TEXT NOT NULL,
    "SIN_LOCATION_ID" TEXT NOT NULL,
    "SIN_START_TIME" DATETIME NOT NULL,
    "SIN_END_TIME" DATETIME NOT NULL,
    "SIN_CAPACITY" INTEGER,
    "SIN_STATUS" TEXT NOT NULL DEFAULT 'scheduled',
    "SIN_INSTRUCTOR" TEXT,
    "SIN_NOTES" TEXT,
    "SIN_WEATHER_CHECKED" BOOLEAN NOT NULL DEFAULT false,
    "SIN_WEATHER_SAFE" BOOLEAN,
    "SIN_WEATHER_DATA" JSONB,
    "SIN_WEATHER_CHECKED_AT" DATETIME,
    "SIN_WEATHER_ALERT_SENT" BOOLEAN NOT NULL DEFAULT false,
    "SIN_MEETING_POINT" TEXT,
    "SIN_ROUTE_DETAILS" JSONB,
    "SIN_ALTERNATIVE_VENUE" TEXT,
    "SIN_CORPORATE_ID" TEXT,
    "SIN_POINTS_AWARDED" INTEGER,
    "SIN_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "SIN_UPDATED_AT" DATETIME NOT NULL,
    CONSTRAINT "MOV_SESSION_INSTANCE_SIN_TENANT_ID_fkey" FOREIGN KEY ("SIN_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MOV_SESSION_INSTANCE_SIN_SESSION_TYPE_ID_fkey" FOREIGN KEY ("SIN_SESSION_TYPE_ID") REFERENCES "MOV_SESSION_TYPE" ("STY_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MOV_SESSION_INSTANCE_SIN_LOCATION_ID_fkey" FOREIGN KEY ("SIN_LOCATION_ID") REFERENCES "MOV_LOCATION" ("LOC_ID") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "MOV_BOOKING" (
    "BOK_ID" TEXT NOT NULL PRIMARY KEY,
    "BOK_TENANT_ID" TEXT NOT NULL,
    "BOK_MEMBER_ID" TEXT NOT NULL,
    "BOK_SESSION_INSTANCE_ID" TEXT NOT NULL,
    "BOK_STATUS" TEXT NOT NULL DEFAULT 'confirmed',
    "BOK_BOOKED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "BOK_ATTENDED_AT" DATETIME,
    "BOK_CANCELLED_AT" DATETIME,
    "BOK_NOTES" TEXT,
    "BOK_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "BOK_UPDATED_AT" DATETIME NOT NULL,
    CONSTRAINT "MOV_BOOKING_BOK_TENANT_ID_fkey" FOREIGN KEY ("BOK_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MOV_BOOKING_BOK_MEMBER_ID_fkey" FOREIGN KEY ("BOK_MEMBER_ID") REFERENCES "MOV_MEMBER" ("MEM_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MOV_BOOKING_BOK_SESSION_INSTANCE_ID_fkey" FOREIGN KEY ("BOK_SESSION_INSTANCE_ID") REFERENCES "MOV_SESSION_INSTANCE" ("SIN_ID") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PLP_MOVEMENT_EVENT" (
    "MVE_ID" TEXT NOT NULL PRIMARY KEY,
    "MVE_TENANT_ID" TEXT NOT NULL,
    "MVE_MEMBER_ID" TEXT NOT NULL,
    "MVE_SESSION_INSTANCE_ID" TEXT,
    "MVE_TYPE" TEXT NOT NULL,
    "MVE_METADATA" JSONB,
    "MVE_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PLP_MOVEMENT_EVENT_MVE_TENANT_ID_fkey" FOREIGN KEY ("MVE_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "PLP_MOVEMENT_EVENT_MVE_MEMBER_ID_fkey" FOREIGN KEY ("MVE_MEMBER_ID") REFERENCES "MOV_MEMBER" ("MEM_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "PLP_MOVEMENT_EVENT_MVE_SESSION_INSTANCE_ID_fkey" FOREIGN KEY ("MVE_SESSION_INSTANCE_ID") REFERENCES "MOV_SESSION_INSTANCE" ("SIN_ID") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "MOV_WAITLIST" (
    "WAI_ID" TEXT NOT NULL PRIMARY KEY,
    "WAI_TENANT_ID" TEXT NOT NULL,
    "WAI_MEMBER_ID" TEXT NOT NULL,
    "WAI_SESSION_INSTANCE_ID" TEXT NOT NULL,
    "WAI_POSITION" INTEGER NOT NULL,
    "WAI_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "WAI_UPDATED_AT" DATETIME NOT NULL,
    CONSTRAINT "MOV_WAITLIST_WAI_TENANT_ID_fkey" FOREIGN KEY ("WAI_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MOV_WAITLIST_WAI_MEMBER_ID_fkey" FOREIGN KEY ("WAI_MEMBER_ID") REFERENCES "MOV_MEMBER" ("MEM_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MOV_WAITLIST_WAI_SESSION_INSTANCE_ID_fkey" FOREIGN KEY ("WAI_SESSION_INSTANCE_ID") REFERENCES "MOV_SESSION_INSTANCE" ("SIN_ID") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "MOV_FAVORITE" (
    "FAV_ID" TEXT NOT NULL PRIMARY KEY,
    "FAV_TENANT_ID" TEXT NOT NULL,
    "FAV_MEMBER_ID" TEXT NOT NULL,
    "FAV_SESSION_TYPE_ID" TEXT NOT NULL,
    "FAV_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "MOV_FAVORITE_FAV_TENANT_ID_fkey" FOREIGN KEY ("FAV_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MOV_FAVORITE_FAV_MEMBER_ID_fkey" FOREIGN KEY ("FAV_MEMBER_ID") REFERENCES "MOV_MEMBER" ("MEM_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MOV_FAVORITE_FAV_SESSION_TYPE_ID_fkey" FOREIGN KEY ("FAV_SESSION_TYPE_ID") REFERENCES "MOV_SESSION_TYPE" ("STY_ID") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "MOV_INVITATION" (
    "INV_ID" TEXT NOT NULL PRIMARY KEY,
    "INV_TENANT_ID" TEXT NOT NULL,
    "INV_SENDER_ID" TEXT NOT NULL,
    "INV_EMAIL" TEXT NOT NULL,
    "INV_NAME" TEXT,
    "INV_ROLE" TEXT NOT NULL DEFAULT 'MEMBER',
    "INV_STATUS" TEXT NOT NULL DEFAULT 'PENDING',
    "INV_MESSAGE" TEXT,
    "INV_CODE" TEXT NOT NULL,
    "INV_EXPIRES_AT" DATETIME NOT NULL,
    "INV_ACCEPTED_AT" DATETIME,
    "INV_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "INV_UPDATED_AT" DATETIME NOT NULL,
    CONSTRAINT "MOV_INVITATION_INV_TENANT_ID_fkey" FOREIGN KEY ("INV_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MOV_INVITATION_INV_SENDER_ID_fkey" FOREIGN KEY ("INV_SENDER_ID") REFERENCES "MOV_MEMBER" ("MEM_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PAY_PAYMENT_REQUEST" (
    "PAY_ID" TEXT NOT NULL PRIMARY KEY,
    "PAY_TENANT_ID" TEXT NOT NULL,
    "PAY_FROM_MEMBER_ID" TEXT,
    "PAY_TO_MEMBER_ID" TEXT NOT NULL,
    "PAY_AMOUNT" REAL NOT NULL,
    "PAY_CURRENCY" TEXT NOT NULL DEFAULT 'KES',
    "PAY_TYPE" TEXT NOT NULL,
    "PAY_DESCRIPTION" TEXT,
    "PAY_STATUS" TEXT NOT NULL DEFAULT 'PENDING',
    "PAY_DUE_DATE" DATETIME,
    "PAY_PAID_AT" DATETIME,
    "PAY_CANCELLED_AT" DATETIME,
    "PAY_METADATA" JSONB,
    "PAY_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "PAY_UPDATED_AT" DATETIME NOT NULL,
    CONSTRAINT "PAY_PAYMENT_REQUEST_PAY_TENANT_ID_fkey" FOREIGN KEY ("PAY_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "PAY_PAYMENT_REQUEST_PAY_FROM_MEMBER_ID_fkey" FOREIGN KEY ("PAY_FROM_MEMBER_ID") REFERENCES "MOV_MEMBER" ("MEM_ID") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "PAY_PAYMENT_REQUEST_PAY_TO_MEMBER_ID_fkey" FOREIGN KEY ("PAY_TO_MEMBER_ID") REFERENCES "MOV_MEMBER" ("MEM_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PAY_MPESA_TRANSACTION" (
    "MPE_ID" TEXT NOT NULL PRIMARY KEY,
    "MPE_TENANT_ID" TEXT NOT NULL,
    "MPE_PAYMENT_REQUEST_ID" TEXT NOT NULL,
    "MPE_MEMBER_ID" TEXT NOT NULL,
    "MPE_PHONE_NUMBER" TEXT NOT NULL,
    "MPE_AMOUNT" REAL NOT NULL,
    "MPE_ACCOUNT_REF" TEXT NOT NULL,
    "MPE_TRANSACTION_DESC" TEXT NOT NULL,
    "MPE_MERCHANT_REQUEST_ID" TEXT,
    "MPE_CHECKOUT_REQUEST_ID" TEXT,
    "MPE_RESPONSE_CODE" TEXT,
    "MPE_RESPONSE_DESC" TEXT,
    "MPE_CUSTOMER_MESSAGE" TEXT,
    "MPE_RECEIPT_NUMBER" TEXT,
    "MPE_TRANSACTION_DATE" DATETIME,
    "MPE_RESULT_CODE" TEXT,
    "MPE_RESULT_DESC" TEXT,
    "MPE_STATUS" TEXT NOT NULL DEFAULT 'INITIATED',
    "MPE_CALLBACK_RECEIVED" BOOLEAN NOT NULL DEFAULT false,
    "MPE_CALLBACK_DATA" JSONB,
    "MPE_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MPE_UPDATED_AT" DATETIME NOT NULL,
    CONSTRAINT "PAY_MPESA_TRANSACTION_MPE_TENANT_ID_fkey" FOREIGN KEY ("MPE_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "PAY_MPESA_TRANSACTION_MPE_PAYMENT_REQUEST_ID_fkey" FOREIGN KEY ("MPE_PAYMENT_REQUEST_ID") REFERENCES "PAY_PAYMENT_REQUEST" ("PAY_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "PAY_MPESA_TRANSACTION_MPE_MEMBER_ID_fkey" FOREIGN KEY ("MPE_MEMBER_ID") REFERENCES "MOV_MEMBER" ("MEM_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PAY_MEMBERSHIP_PLAN" (
    "MBP_ID" TEXT NOT NULL PRIMARY KEY,
    "MBP_TENANT_ID" TEXT NOT NULL,
    "MBP_NAME" TEXT NOT NULL,
    "MBP_DESCRIPTION" TEXT,
    "MBP_PRICE" REAL NOT NULL,
    "MBP_CURRENCY" TEXT NOT NULL DEFAULT 'KES',
    "MBP_BILLING_CYCLE" TEXT NOT NULL DEFAULT 'monthly',
    "MBP_FEATURES" JSONB,
    "MBP_SESSIONS_PER_MONTH" INTEGER,
    "MBP_ACCESS_LEVEL" TEXT NOT NULL DEFAULT 'standard',
    "MBP_IS_ACTIVE" BOOLEAN NOT NULL DEFAULT true,
    "MBP_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MBP_UPDATED_AT" DATETIME NOT NULL,
    CONSTRAINT "PAY_MEMBERSHIP_PLAN_MBP_TENANT_ID_fkey" FOREIGN KEY ("MBP_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PAY_MEMBERSHIP_SUBSCRIPTION" (
    "MBS_ID" TEXT NOT NULL PRIMARY KEY,
    "MBS_TENANT_ID" TEXT NOT NULL,
    "MBS_MEMBER_ID" TEXT NOT NULL,
    "MBS_PLAN_ID" TEXT NOT NULL,
    "MBS_STATUS" TEXT NOT NULL DEFAULT 'ACTIVE',
    "MBS_START_DATE" DATETIME NOT NULL,
    "MBS_END_DATE" DATETIME NOT NULL,
    "MBS_NEXT_BILLING" DATETIME NOT NULL,
    "MBS_AUTO_RENEW" BOOLEAN NOT NULL DEFAULT true,
    "MBS_CANCELLED_AT" DATETIME,
    "MBS_CANCELLATION_REASON" TEXT,
    "MBS_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MBS_UPDATED_AT" DATETIME NOT NULL,
    CONSTRAINT "PAY_MEMBERSHIP_SUBSCRIPTION_MBS_TENANT_ID_fkey" FOREIGN KEY ("MBS_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "PAY_MEMBERSHIP_SUBSCRIPTION_MBS_MEMBER_ID_fkey" FOREIGN KEY ("MBS_MEMBER_ID") REFERENCES "MOV_MEMBER" ("MEM_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "PAY_MEMBERSHIP_SUBSCRIPTION_MBS_PLAN_ID_fkey" FOREIGN KEY ("MBS_PLAN_ID") REFERENCES "PAY_MEMBERSHIP_PLAN" ("MBP_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PAY_TRAINER_EARNINGS" (
    "TEA_ID" TEXT NOT NULL PRIMARY KEY,
    "TEA_TENANT_ID" TEXT NOT NULL,
    "TEA_TRAINER_ID" TEXT NOT NULL,
    "TEA_MONTH" INTEGER NOT NULL,
    "TEA_YEAR" INTEGER NOT NULL,
    "TEA_TOTAL_REVENUE" REAL NOT NULL DEFAULT 0,
    "TEA_PLATFORM_FEE" REAL NOT NULL DEFAULT 0,
    "TEA_NET_EARNINGS" REAL NOT NULL DEFAULT 0,
    "TEA_PAYOUT_AMOUNT" REAL NOT NULL DEFAULT 0,
    "TEA_PAYOUT_DATE" DATETIME,
    "TEA_PAYOUT_METHOD" TEXT,
    "TEA_PAYOUT_REFERENCE" TEXT,
    "TEA_STATUS" TEXT NOT NULL DEFAULT 'PENDING',
    "TEA_METADATA" JSONB,
    "TEA_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TEA_UPDATED_AT" DATETIME NOT NULL,
    CONSTRAINT "PAY_TRAINER_EARNINGS_TEA_TENANT_ID_fkey" FOREIGN KEY ("TEA_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "PAY_TRAINER_EARNINGS_TEA_TRAINER_ID_fkey" FOREIGN KEY ("TEA_TRAINER_ID") REFERENCES "MOV_MEMBER" ("MEM_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "MOV_TENANT_TEN_CODE_key" ON "MOV_TENANT"("TEN_CODE");

-- CreateIndex
CREATE INDEX "MOV_TENANT_TEN_CODE_idx" ON "MOV_TENANT"("TEN_CODE");

-- CreateIndex
CREATE UNIQUE INDEX "MOV_MEMBER_MEM_GOOGLE_ID_key" ON "MOV_MEMBER"("MEM_GOOGLE_ID");

-- CreateIndex
CREATE UNIQUE INDEX "MOV_MEMBER_MEM_TRAINER_CODE_key" ON "MOV_MEMBER"("MEM_TRAINER_CODE");

-- CreateIndex
CREATE INDEX "MOV_MEMBER_MEM_TENANT_ID_idx" ON "MOV_MEMBER"("MEM_TENANT_ID");

-- CreateIndex
CREATE INDEX "MOV_MEMBER_MEM_ROLE_idx" ON "MOV_MEMBER"("MEM_ROLE");

-- CreateIndex
CREATE INDEX "MOV_MEMBER_MEM_PROFILE_COMPLETED_idx" ON "MOV_MEMBER"("MEM_PROFILE_COMPLETED");

-- CreateIndex
CREATE INDEX "MOV_MEMBER_MEM_TRAINER_CODE_idx" ON "MOV_MEMBER"("MEM_TRAINER_CODE");

-- CreateIndex
CREATE INDEX "MOV_MEMBER_MEM_TRAINER_TYPE_idx" ON "MOV_MEMBER"("MEM_TRAINER_TYPE");

-- CreateIndex
CREATE UNIQUE INDEX "MOV_MEMBER_MEM_EMAIL_MEM_TENANT_ID_key" ON "MOV_MEMBER"("MEM_EMAIL", "MEM_TENANT_ID");

-- CreateIndex
CREATE INDEX "MOV_LOCATION_LOC_TENANT_ID_idx" ON "MOV_LOCATION"("LOC_TENANT_ID");

-- CreateIndex
CREATE INDEX "MOV_LOCATION_LOC_IS_ACTIVE_idx" ON "MOV_LOCATION"("LOC_IS_ACTIVE");

-- CreateIndex
CREATE INDEX "MOV_LOCATION_LOC_COUNTRY_LOC_PROVINCE_LOC_CITY_idx" ON "MOV_LOCATION"("LOC_COUNTRY", "LOC_PROVINCE", "LOC_CITY");

-- CreateIndex
CREATE INDEX "MOV_LOCATION_LOC_LATITUDE_LOC_LONGITUDE_idx" ON "MOV_LOCATION"("LOC_LATITUDE", "LOC_LONGITUDE");

-- CreateIndex
CREATE INDEX "MOV_LOCATION_LOC_CORPORATE_ID_idx" ON "MOV_LOCATION"("LOC_CORPORATE_ID");

-- CreateIndex
CREATE INDEX "MOV_LOCATION_LOC_TYPE_idx" ON "MOV_LOCATION"("LOC_TYPE");

-- CreateIndex
CREATE UNIQUE INDEX "MOV_LOCATION_LOC_TENANT_ID_LOC_NAME_key" ON "MOV_LOCATION"("LOC_TENANT_ID", "LOC_NAME");

-- CreateIndex
CREATE INDEX "MOV_SESSION_TYPE_STY_TENANT_ID_idx" ON "MOV_SESSION_TYPE"("STY_TENANT_ID");

-- CreateIndex
CREATE INDEX "MOV_SESSION_TYPE_STY_CATEGORY_idx" ON "MOV_SESSION_TYPE"("STY_CATEGORY");

-- CreateIndex
CREATE INDEX "MOV_SESSION_TYPE_STY_IS_ACTIVE_idx" ON "MOV_SESSION_TYPE"("STY_IS_ACTIVE");

-- CreateIndex
CREATE INDEX "MOV_SESSION_TYPE_STY_IS_OUTDOOR_idx" ON "MOV_SESSION_TYPE"("STY_IS_OUTDOOR");

-- CreateIndex
CREATE INDEX "MOV_SESSION_TYPE_STY_CORPORATE_APPROVED_idx" ON "MOV_SESSION_TYPE"("STY_CORPORATE_APPROVED");

-- CreateIndex
CREATE UNIQUE INDEX "MOV_SESSION_TYPE_STY_TENANT_ID_STY_NAME_key" ON "MOV_SESSION_TYPE"("STY_TENANT_ID", "STY_NAME");

-- CreateIndex
CREATE INDEX "MOV_SESSION_INSTANCE_SIN_TENANT_ID_idx" ON "MOV_SESSION_INSTANCE"("SIN_TENANT_ID");

-- CreateIndex
CREATE INDEX "MOV_SESSION_INSTANCE_SIN_START_TIME_idx" ON "MOV_SESSION_INSTANCE"("SIN_START_TIME");

-- CreateIndex
CREATE INDEX "MOV_SESSION_INSTANCE_SIN_STATUS_idx" ON "MOV_SESSION_INSTANCE"("SIN_STATUS");

-- CreateIndex
CREATE INDEX "MOV_SESSION_INSTANCE_SIN_SESSION_TYPE_ID_idx" ON "MOV_SESSION_INSTANCE"("SIN_SESSION_TYPE_ID");

-- CreateIndex
CREATE INDEX "MOV_SESSION_INSTANCE_SIN_LOCATION_ID_idx" ON "MOV_SESSION_INSTANCE"("SIN_LOCATION_ID");

-- CreateIndex
CREATE INDEX "MOV_SESSION_INSTANCE_SIN_WEATHER_SAFE_idx" ON "MOV_SESSION_INSTANCE"("SIN_WEATHER_SAFE");

-- CreateIndex
CREATE INDEX "MOV_SESSION_INSTANCE_SIN_CORPORATE_ID_idx" ON "MOV_SESSION_INSTANCE"("SIN_CORPORATE_ID");

-- CreateIndex
CREATE UNIQUE INDEX "MOV_SESSION_INSTANCE_SIN_LOCATION_ID_SIN_START_TIME_key" ON "MOV_SESSION_INSTANCE"("SIN_LOCATION_ID", "SIN_START_TIME");

-- CreateIndex
CREATE INDEX "MOV_BOOKING_BOK_TENANT_ID_idx" ON "MOV_BOOKING"("BOK_TENANT_ID");

-- CreateIndex
CREATE INDEX "MOV_BOOKING_BOK_MEMBER_ID_idx" ON "MOV_BOOKING"("BOK_MEMBER_ID");

-- CreateIndex
CREATE INDEX "MOV_BOOKING_BOK_SESSION_INSTANCE_ID_idx" ON "MOV_BOOKING"("BOK_SESSION_INSTANCE_ID");

-- CreateIndex
CREATE INDEX "MOV_BOOKING_BOK_STATUS_idx" ON "MOV_BOOKING"("BOK_STATUS");

-- CreateIndex
CREATE INDEX "MOV_BOOKING_BOK_BOOKED_AT_idx" ON "MOV_BOOKING"("BOK_BOOKED_AT");

-- CreateIndex
CREATE UNIQUE INDEX "MOV_BOOKING_BOK_MEMBER_ID_BOK_SESSION_INSTANCE_ID_key" ON "MOV_BOOKING"("BOK_MEMBER_ID", "BOK_SESSION_INSTANCE_ID");

-- CreateIndex
CREATE INDEX "PLP_MOVEMENT_EVENT_MVE_TENANT_ID_idx" ON "PLP_MOVEMENT_EVENT"("MVE_TENANT_ID");

-- CreateIndex
CREATE INDEX "PLP_MOVEMENT_EVENT_MVE_MEMBER_ID_idx" ON "PLP_MOVEMENT_EVENT"("MVE_MEMBER_ID");

-- CreateIndex
CREATE INDEX "PLP_MOVEMENT_EVENT_MVE_CREATED_AT_idx" ON "PLP_MOVEMENT_EVENT"("MVE_CREATED_AT");

-- CreateIndex
CREATE INDEX "PLP_MOVEMENT_EVENT_MVE_TYPE_idx" ON "PLP_MOVEMENT_EVENT"("MVE_TYPE");

-- CreateIndex
CREATE INDEX "PLP_MOVEMENT_EVENT_MVE_SESSION_INSTANCE_ID_idx" ON "PLP_MOVEMENT_EVENT"("MVE_SESSION_INSTANCE_ID");

-- CreateIndex
CREATE INDEX "MOV_WAITLIST_WAI_TENANT_ID_idx" ON "MOV_WAITLIST"("WAI_TENANT_ID");

-- CreateIndex
CREATE INDEX "MOV_WAITLIST_WAI_MEMBER_ID_idx" ON "MOV_WAITLIST"("WAI_MEMBER_ID");

-- CreateIndex
CREATE INDEX "MOV_WAITLIST_WAI_SESSION_INSTANCE_ID_idx" ON "MOV_WAITLIST"("WAI_SESSION_INSTANCE_ID");

-- CreateIndex
CREATE UNIQUE INDEX "MOV_WAITLIST_WAI_MEMBER_ID_WAI_SESSION_INSTANCE_ID_key" ON "MOV_WAITLIST"("WAI_MEMBER_ID", "WAI_SESSION_INSTANCE_ID");

-- CreateIndex
CREATE INDEX "MOV_FAVORITE_FAV_TENANT_ID_idx" ON "MOV_FAVORITE"("FAV_TENANT_ID");

-- CreateIndex
CREATE INDEX "MOV_FAVORITE_FAV_MEMBER_ID_idx" ON "MOV_FAVORITE"("FAV_MEMBER_ID");

-- CreateIndex
CREATE INDEX "MOV_FAVORITE_FAV_SESSION_TYPE_ID_idx" ON "MOV_FAVORITE"("FAV_SESSION_TYPE_ID");

-- CreateIndex
CREATE UNIQUE INDEX "MOV_FAVORITE_FAV_MEMBER_ID_FAV_SESSION_TYPE_ID_key" ON "MOV_FAVORITE"("FAV_MEMBER_ID", "FAV_SESSION_TYPE_ID");

-- CreateIndex
CREATE UNIQUE INDEX "MOV_INVITATION_INV_CODE_key" ON "MOV_INVITATION"("INV_CODE");

-- CreateIndex
CREATE INDEX "MOV_INVITATION_INV_TENANT_ID_idx" ON "MOV_INVITATION"("INV_TENANT_ID");

-- CreateIndex
CREATE INDEX "MOV_INVITATION_INV_SENDER_ID_idx" ON "MOV_INVITATION"("INV_SENDER_ID");

-- CreateIndex
CREATE INDEX "MOV_INVITATION_INV_CODE_idx" ON "MOV_INVITATION"("INV_CODE");

-- CreateIndex
CREATE INDEX "MOV_INVITATION_INV_EMAIL_idx" ON "MOV_INVITATION"("INV_EMAIL");

-- CreateIndex
CREATE INDEX "PAY_PAYMENT_REQUEST_PAY_TENANT_ID_idx" ON "PAY_PAYMENT_REQUEST"("PAY_TENANT_ID");

-- CreateIndex
CREATE INDEX "PAY_PAYMENT_REQUEST_PAY_FROM_MEMBER_ID_idx" ON "PAY_PAYMENT_REQUEST"("PAY_FROM_MEMBER_ID");

-- CreateIndex
CREATE INDEX "PAY_PAYMENT_REQUEST_PAY_TO_MEMBER_ID_idx" ON "PAY_PAYMENT_REQUEST"("PAY_TO_MEMBER_ID");

-- CreateIndex
CREATE INDEX "PAY_PAYMENT_REQUEST_PAY_STATUS_idx" ON "PAY_PAYMENT_REQUEST"("PAY_STATUS");

-- CreateIndex
CREATE INDEX "PAY_PAYMENT_REQUEST_PAY_TYPE_idx" ON "PAY_PAYMENT_REQUEST"("PAY_TYPE");

-- CreateIndex
CREATE INDEX "PAY_PAYMENT_REQUEST_PAY_DUE_DATE_idx" ON "PAY_PAYMENT_REQUEST"("PAY_DUE_DATE");

-- CreateIndex
CREATE INDEX "PAY_PAYMENT_REQUEST_PAY_CREATED_AT_idx" ON "PAY_PAYMENT_REQUEST"("PAY_CREATED_AT");

-- CreateIndex
CREATE UNIQUE INDEX "PAY_MPESA_TRANSACTION_MPE_CHECKOUT_REQUEST_ID_key" ON "PAY_MPESA_TRANSACTION"("MPE_CHECKOUT_REQUEST_ID");

-- CreateIndex
CREATE UNIQUE INDEX "PAY_MPESA_TRANSACTION_MPE_RECEIPT_NUMBER_key" ON "PAY_MPESA_TRANSACTION"("MPE_RECEIPT_NUMBER");

-- CreateIndex
CREATE INDEX "PAY_MPESA_TRANSACTION_MPE_TENANT_ID_idx" ON "PAY_MPESA_TRANSACTION"("MPE_TENANT_ID");

-- CreateIndex
CREATE INDEX "PAY_MPESA_TRANSACTION_MPE_PAYMENT_REQUEST_ID_idx" ON "PAY_MPESA_TRANSACTION"("MPE_PAYMENT_REQUEST_ID");

-- CreateIndex
CREATE INDEX "PAY_MPESA_TRANSACTION_MPE_MEMBER_ID_idx" ON "PAY_MPESA_TRANSACTION"("MPE_MEMBER_ID");

-- CreateIndex
CREATE INDEX "PAY_MPESA_TRANSACTION_MPE_STATUS_idx" ON "PAY_MPESA_TRANSACTION"("MPE_STATUS");

-- CreateIndex
CREATE INDEX "PAY_MPESA_TRANSACTION_MPE_CHECKOUT_REQUEST_ID_idx" ON "PAY_MPESA_TRANSACTION"("MPE_CHECKOUT_REQUEST_ID");

-- CreateIndex
CREATE INDEX "PAY_MPESA_TRANSACTION_MPE_RECEIPT_NUMBER_idx" ON "PAY_MPESA_TRANSACTION"("MPE_RECEIPT_NUMBER");

-- CreateIndex
CREATE INDEX "PAY_MEMBERSHIP_PLAN_MBP_TENANT_ID_idx" ON "PAY_MEMBERSHIP_PLAN"("MBP_TENANT_ID");

-- CreateIndex
CREATE INDEX "PAY_MEMBERSHIP_PLAN_MBP_IS_ACTIVE_idx" ON "PAY_MEMBERSHIP_PLAN"("MBP_IS_ACTIVE");

-- CreateIndex
CREATE INDEX "PAY_MEMBERSHIP_SUBSCRIPTION_MBS_TENANT_ID_idx" ON "PAY_MEMBERSHIP_SUBSCRIPTION"("MBS_TENANT_ID");

-- CreateIndex
CREATE INDEX "PAY_MEMBERSHIP_SUBSCRIPTION_MBS_MEMBER_ID_idx" ON "PAY_MEMBERSHIP_SUBSCRIPTION"("MBS_MEMBER_ID");

-- CreateIndex
CREATE INDEX "PAY_MEMBERSHIP_SUBSCRIPTION_MBS_PLAN_ID_idx" ON "PAY_MEMBERSHIP_SUBSCRIPTION"("MBS_PLAN_ID");

-- CreateIndex
CREATE INDEX "PAY_MEMBERSHIP_SUBSCRIPTION_MBS_STATUS_idx" ON "PAY_MEMBERSHIP_SUBSCRIPTION"("MBS_STATUS");

-- CreateIndex
CREATE INDEX "PAY_MEMBERSHIP_SUBSCRIPTION_MBS_NEXT_BILLING_idx" ON "PAY_MEMBERSHIP_SUBSCRIPTION"("MBS_NEXT_BILLING");

-- CreateIndex
CREATE INDEX "PAY_TRAINER_EARNINGS_TEA_TENANT_ID_idx" ON "PAY_TRAINER_EARNINGS"("TEA_TENANT_ID");

-- CreateIndex
CREATE INDEX "PAY_TRAINER_EARNINGS_TEA_TRAINER_ID_idx" ON "PAY_TRAINER_EARNINGS"("TEA_TRAINER_ID");

-- CreateIndex
CREATE INDEX "PAY_TRAINER_EARNINGS_TEA_STATUS_idx" ON "PAY_TRAINER_EARNINGS"("TEA_STATUS");

-- CreateIndex
CREATE INDEX "PAY_TRAINER_EARNINGS_TEA_YEAR_TEA_MONTH_idx" ON "PAY_TRAINER_EARNINGS"("TEA_YEAR", "TEA_MONTH");

-- CreateIndex
CREATE UNIQUE INDEX "PAY_TRAINER_EARNINGS_TEA_TRAINER_ID_TEA_MONTH_TEA_YEAR_key" ON "PAY_TRAINER_EARNINGS"("TEA_TRAINER_ID", "TEA_MONTH", "TEA_YEAR");
