-- AlterTable
ALTER TABLE "MOV_LOCATION" ADD COLUMN "LOC_AMENITIES" TEXT;
ALTER TABLE "MOV_LOCATION" ADD COLUMN "LOC_DESCRIPTION" TEXT;
ALTER TABLE "MOV_LOCATION" ADD COLUMN "LOC_EQUIPMENT" TEXT;
ALTER TABLE "MOV_LOCATION" ADD COLUMN "LOC_OPERATING_HOURS" TEXT;
ALTER TABLE "MOV_LOCATION" ADD COLUMN "LOC_PHOTOS" TEXT;
ALTER TABLE "MOV_LOCATION" ADD COLUMN "LOC_SERVICES" TEXT;
