/*
  Warnings:

  - You are about to alter the column `MVE_METADATA` on the `PLP_MOVEMENT_EVENT` table. The data in that column could be lost. The data in that column will be cast from `String` to `Json`.

*/
-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_MOV_MEMBER" (
    "MEM_ID" TEXT NOT NULL PRIMARY KEY,
    "MEM_TENANT_ID" TEXT NOT NULL,
    "MEM_EMAIL" TEXT NOT NULL,
    "MEM_PASSWORD_HASH" TEXT,
    "MEM_NAME" TEXT,
    "MEM_GOOGLE_ID" TEXT,
    "MEM_AVATAR_URL" TEXT,
    "MEM_ROLE" TEXT NOT NULL DEFAULT 'MEMBER',
    "MEM_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MEM_UPDATED_AT" DATETIME NOT NULL,
    "MEM_PHONE_NUMBER" TEXT,
    "MEM_DATE_OF_BIRTH" TEXT,
    "MEM_GENDER" TEXT,
    "MEM_PROFILE_PHOTO" TEXT,
    "MEM_OWNER_PROFILE" JSONB,
    "MEM_TRAINER_PROFILE" JSONB,
    "MEM_CLIENT_PROFILE" JSONB,
    "MEM_STAFF_PROFILE" JSONB,
    "MEM_PROFILE_COMPLETED" BOOLEAN NOT NULL DEFAULT false,
    "MEM_ONBOARDING_STEP" INTEGER,
    CONSTRAINT "MOV_MEMBER_MEM_TENANT_ID_fkey" FOREIGN KEY ("MEM_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_MOV_MEMBER" ("MEM_AVATAR_URL", "MEM_CREATED_AT", "MEM_EMAIL", "MEM_GOOGLE_ID", "MEM_ID", "MEM_NAME", "MEM_PASSWORD_HASH", "MEM_ROLE", "MEM_TENANT_ID", "MEM_UPDATED_AT") SELECT "MEM_AVATAR_URL", "MEM_CREATED_AT", "MEM_EMAIL", "MEM_GOOGLE_ID", "MEM_ID", "MEM_NAME", "MEM_PASSWORD_HASH", "MEM_ROLE", "MEM_TENANT_ID", "MEM_UPDATED_AT" FROM "MOV_MEMBER";
DROP TABLE "MOV_MEMBER";
ALTER TABLE "new_MOV_MEMBER" RENAME TO "MOV_MEMBER";
CREATE UNIQUE INDEX "MOV_MEMBER_MEM_GOOGLE_ID_key" ON "MOV_MEMBER"("MEM_GOOGLE_ID");
CREATE INDEX "MOV_MEMBER_MEM_TENANT_ID_idx" ON "MOV_MEMBER"("MEM_TENANT_ID");
CREATE INDEX "MOV_MEMBER_MEM_ROLE_idx" ON "MOV_MEMBER"("MEM_ROLE");
CREATE INDEX "MOV_MEMBER_MEM_PROFILE_COMPLETED_idx" ON "MOV_MEMBER"("MEM_PROFILE_COMPLETED");
CREATE UNIQUE INDEX "MOV_MEMBER_MEM_EMAIL_MEM_TENANT_ID_key" ON "MOV_MEMBER"("MEM_EMAIL", "MEM_TENANT_ID");
CREATE TABLE "new_PLP_MOVEMENT_EVENT" (
    "MVE_ID" TEXT NOT NULL PRIMARY KEY,
    "MVE_TENANT_ID" TEXT NOT NULL,
    "MVE_MEMBER_ID" TEXT NOT NULL,
    "MVE_SESSION_INSTANCE_ID" TEXT,
    "MVE_TYPE" TEXT NOT NULL,
    "MVE_METADATA" JSONB,
    "MVE_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PLP_MOVEMENT_EVENT_MVE_TENANT_ID_fkey" FOREIGN KEY ("MVE_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "PLP_MOVEMENT_EVENT_MVE_MEMBER_ID_fkey" FOREIGN KEY ("MVE_MEMBER_ID") REFERENCES "MOV_MEMBER" ("MEM_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "PLP_MOVEMENT_EVENT_MVE_SESSION_INSTANCE_ID_fkey" FOREIGN KEY ("MVE_SESSION_INSTANCE_ID") REFERENCES "MOV_SESSION_INSTANCE" ("SIN_ID") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_PLP_MOVEMENT_EVENT" ("MVE_CREATED_AT", "MVE_ID", "MVE_MEMBER_ID", "MVE_METADATA", "MVE_SESSION_INSTANCE_ID", "MVE_TENANT_ID", "MVE_TYPE") SELECT "MVE_CREATED_AT", "MVE_ID", "MVE_MEMBER_ID", "MVE_METADATA", "MVE_SESSION_INSTANCE_ID", "MVE_TENANT_ID", "MVE_TYPE" FROM "PLP_MOVEMENT_EVENT";
DROP TABLE "PLP_MOVEMENT_EVENT";
ALTER TABLE "new_PLP_MOVEMENT_EVENT" RENAME TO "PLP_MOVEMENT_EVENT";
CREATE INDEX "PLP_MOVEMENT_EVENT_MVE_TENANT_ID_idx" ON "PLP_MOVEMENT_EVENT"("MVE_TENANT_ID");
CREATE INDEX "PLP_MOVEMENT_EVENT_MVE_MEMBER_ID_idx" ON "PLP_MOVEMENT_EVENT"("MVE_MEMBER_ID");
CREATE INDEX "PLP_MOVEMENT_EVENT_MVE_CREATED_AT_idx" ON "PLP_MOVEMENT_EVENT"("MVE_CREATED_AT");
CREATE INDEX "PLP_MOVEMENT_EVENT_MVE_TYPE_idx" ON "PLP_MOVEMENT_EVENT"("MVE_TYPE");
CREATE INDEX "PLP_MOVEMENT_EVENT_MVE_SESSION_INSTANCE_ID_idx" ON "PLP_MOVEMENT_EVENT"("MVE_SESSION_INSTANCE_ID");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
