-- ZMOS Naming Convention Migration
-- This migration renames tables and columns to follow official ZMOS conventions
-- Domain Prefixes: MOV_ (MoveOS), PLP_ (PulseLoop)
-- Table Prefixes: TEN_, MEM_, LOC_, STY_, SIN_, BOK_, MVE_, WAI_, FAV_

-- =============================================================================
-- TENANT TABLE: Tenant → MOV_TENANT with TEN_ column prefix
-- =============================================================================

PRAGMA foreign_keys=OFF;

CREATE TABLE "MOV_TENANT" (
    "TEN_ID" TEXT NOT NULL PRIMARY KEY,
    "TEN_NAME" TEXT NOT NULL,
    "TEN_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TEN_UPDATED_AT" DATETIME NOT NULL
);

INSERT INTO "MOV_TENANT" ("TEN_ID", "TEN_NAME", "TEN_CREATED_AT", "TEN_UPDATED_AT")
SELECT "id", "name", "createdAt", "updatedAt"
FROM "Tenant";

DROP TABLE "Tenant";

-- =============================================================================
-- MEMBER TABLE: Member → MOV_MEMBER with MEM_ column prefix
-- =============================================================================

CREATE TABLE "MOV_MEMBER" (
    "MEM_ID" TEXT NOT NULL PRIMARY KEY,
    "MEM_TENANT_ID" TEXT NOT NULL,
    "MEM_EMAIL" TEXT NOT NULL,
    "MEM_PASSWORD_HASH" TEXT,
    "MEM_NAME" TEXT,
    "MEM_GOOGLE_ID" TEXT,
    "MEM_AVATAR_URL" TEXT,
    "MEM_ROLE" TEXT NOT NULL DEFAULT 'MEMBER',
    "MEM_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MEM_UPDATED_AT" DATETIME NOT NULL,
    CONSTRAINT "MOV_MEMBER_MEM_TENANT_ID_fkey" FOREIGN KEY ("MEM_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO "MOV_MEMBER" ("MEM_ID", "MEM_TENANT_ID", "MEM_EMAIL", "MEM_PASSWORD_HASH", "MEM_NAME", "MEM_GOOGLE_ID", "MEM_AVATAR_URL", "MEM_ROLE", "MEM_CREATED_AT", "MEM_UPDATED_AT")
SELECT "id", "tenantId", "email", "passwordHash", "name", "googleId", "avatarUrl", "role", "createdAt", "updatedAt"
FROM "Member";

DROP TABLE "Member";

CREATE UNIQUE INDEX "MOV_MEMBER_MEM_GOOGLE_ID_key" ON "MOV_MEMBER"("MEM_GOOGLE_ID");
CREATE UNIQUE INDEX "MOV_MEMBER_MEM_EMAIL_MEM_TENANT_ID_key" ON "MOV_MEMBER"("MEM_EMAIL", "MEM_TENANT_ID");
CREATE INDEX "MOV_MEMBER_MEM_TENANT_ID_idx" ON "MOV_MEMBER"("MEM_TENANT_ID");
CREATE INDEX "MOV_MEMBER_MEM_ROLE_idx" ON "MOV_MEMBER"("MEM_ROLE");

-- =============================================================================
-- LOCATION TABLE: Location → MOV_LOCATION with LOC_ column prefix (if exists)
-- =============================================================================

CREATE TABLE "MOV_LOCATION" (
    "LOC_ID" TEXT NOT NULL PRIMARY KEY,
    "LOC_TENANT_ID" TEXT NOT NULL,
    "LOC_NAME" TEXT NOT NULL,
    "LOC_ADDRESS" TEXT,
    "LOC_CAPACITY" INTEGER,
    "LOC_TIMEZONE" TEXT NOT NULL DEFAULT 'UTC',
    "LOC_IS_ACTIVE" BOOLEAN NOT NULL DEFAULT 1,
    "LOC_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "LOC_UPDATED_AT" DATETIME NOT NULL,
    CONSTRAINT "MOV_LOCATION_LOC_TENANT_ID_fkey" FOREIGN KEY ("LOC_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE
);

-- Only migrate if Location table exists
INSERT INTO "MOV_LOCATION" ("LOC_ID", "LOC_TENANT_ID", "LOC_NAME", "LOC_ADDRESS", "LOC_CAPACITY", "LOC_TIMEZONE", "LOC_IS_ACTIVE", "LOC_CREATED_AT", "LOC_UPDATED_AT")
SELECT "id", "tenantId", "name", "address", "capacity", "timezone", "isActive", "createdAt", "updatedAt"
FROM "Location"
WHERE EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='Location');

DROP TABLE IF EXISTS "Location";

CREATE UNIQUE INDEX "MOV_LOCATION_LOC_TENANT_ID_LOC_NAME_key" ON "MOV_LOCATION"("LOC_TENANT_ID", "LOC_NAME");
CREATE INDEX "MOV_LOCATION_LOC_TENANT_ID_idx" ON "MOV_LOCATION"("LOC_TENANT_ID");
CREATE INDEX "MOV_LOCATION_LOC_IS_ACTIVE_idx" ON "MOV_LOCATION"("LOC_IS_ACTIVE");

-- =============================================================================
-- SESSION_TYPE TABLE: SessionType → MOV_SESSION_TYPE with STY_ column prefix
-- =============================================================================

CREATE TABLE "MOV_SESSION_TYPE" (
    "STY_ID" TEXT NOT NULL PRIMARY KEY,
    "STY_TENANT_ID" TEXT NOT NULL,
    "STY_NAME" TEXT NOT NULL,
    "STY_DESCRIPTION" TEXT,
    "STY_DURATION_MIN" INTEGER NOT NULL,
    "STY_CATEGORY" TEXT NOT NULL,
    "STY_MAX_CAPACITY" INTEGER,
    "STY_DIFFICULTY" TEXT NOT NULL DEFAULT 'intermediate',
    "STY_IS_ACTIVE" BOOLEAN NOT NULL DEFAULT 1,
    "STY_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "STY_UPDATED_AT" DATETIME NOT NULL,
    CONSTRAINT "MOV_SESSION_TYPE_STY_TENANT_ID_fkey" FOREIGN KEY ("STY_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO "MOV_SESSION_TYPE" ("STY_ID", "STY_TENANT_ID", "STY_NAME", "STY_DESCRIPTION", "STY_DURATION_MIN", "STY_CATEGORY", "STY_MAX_CAPACITY", "STY_DIFFICULTY", "STY_IS_ACTIVE", "STY_CREATED_AT", "STY_UPDATED_AT")
SELECT "id", "tenantId", "name", "description", "durationMin", "category", "maxCapacity", "difficulty", "isActive", "createdAt", "updatedAt"
FROM "SessionType"
WHERE EXISTS (SELECT 1 FROM sqlite_master WHERE type='table' AND name='SessionType');

DROP TABLE IF EXISTS "SessionType";

CREATE UNIQUE INDEX "MOV_SESSION_TYPE_STY_TENANT_ID_STY_NAME_key" ON "MOV_SESSION_TYPE"("STY_TENANT_ID", "STY_NAME");
CREATE INDEX "MOV_SESSION_TYPE_STY_TENANT_ID_idx" ON "MOV_SESSION_TYPE"("STY_TENANT_ID");
CREATE INDEX "MOV_SESSION_TYPE_STY_CATEGORY_idx" ON "MOV_SESSION_TYPE"("STY_CATEGORY");
CREATE INDEX "MOV_SESSION_TYPE_STY_IS_ACTIVE_idx" ON "MOV_SESSION_TYPE"("STY_IS_ACTIVE");

-- =============================================================================
-- SESSION_INSTANCE TABLE: SessionInstance → MOV_SESSION_INSTANCE with SIN_ prefix
-- =============================================================================

CREATE TABLE "MOV_SESSION_INSTANCE" (
    "SIN_ID" TEXT NOT NULL PRIMARY KEY,
    "SIN_TENANT_ID" TEXT NOT NULL,
    "SIN_SESSION_TYPE_ID" TEXT NOT NULL,
    "SIN_LOCATION_ID" TEXT NOT NULL,
    "SIN_START_TIME" DATETIME NOT NULL,
    "SIN_END_TIME" DATETIME NOT NULL,
    "SIN_CAPACITY" INTEGER,
    "SIN_STATUS" TEXT NOT NULL DEFAULT 'scheduled',
    "SIN_INSTRUCTOR" TEXT,
    "SIN_NOTES" TEXT,
    "SIN_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "SIN_UPDATED_AT" DATETIME NOT NULL,
    CONSTRAINT "MOV_SESSION_INSTANCE_SIN_TENANT_ID_fkey" FOREIGN KEY ("SIN_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MOV_SESSION_INSTANCE_SIN_SESSION_TYPE_ID_fkey" FOREIGN KEY ("SIN_SESSION_TYPE_ID") REFERENCES "MOV_SESSION_TYPE" ("STY_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MOV_SESSION_INSTANCE_SIN_LOCATION_ID_fkey" FOREIGN KEY ("SIN_LOCATION_ID") REFERENCES "MOV_LOCATION" ("LOC_ID") ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO "MOV_SESSION_INSTANCE" SELECT * FROM "SessionInstance" WHERE 1=0;
DROP TABLE IF EXISTS "SessionInstance";

CREATE UNIQUE INDEX "MOV_SESSION_INSTANCE_SIN_LOCATION_ID_SIN_START_TIME_key" ON "MOV_SESSION_INSTANCE"("SIN_LOCATION_ID", "SIN_START_TIME");
CREATE INDEX "MOV_SESSION_INSTANCE_SIN_TENANT_ID_idx" ON "MOV_SESSION_INSTANCE"("SIN_TENANT_ID");
CREATE INDEX "MOV_SESSION_INSTANCE_SIN_START_TIME_idx" ON "MOV_SESSION_INSTANCE"("SIN_START_TIME");
CREATE INDEX "MOV_SESSION_INSTANCE_SIN_STATUS_idx" ON "MOV_SESSION_INSTANCE"("SIN_STATUS");
CREATE INDEX "MOV_SESSION_INSTANCE_SIN_SESSION_TYPE_ID_idx" ON "MOV_SESSION_INSTANCE"("SIN_SESSION_TYPE_ID");
CREATE INDEX "MOV_SESSION_INSTANCE_SIN_LOCATION_ID_idx" ON "MOV_SESSION_INSTANCE"("SIN_LOCATION_ID");

-- =============================================================================
-- BOOKING TABLE: Booking → MOV_BOOKING with BOK_ prefix
-- =============================================================================

CREATE TABLE "MOV_BOOKING" (
    "BOK_ID" TEXT NOT NULL PRIMARY KEY,
    "BOK_TENANT_ID" TEXT NOT NULL,
    "BOK_MEMBER_ID" TEXT NOT NULL,
    "BOK_SESSION_INSTANCE_ID" TEXT NOT NULL,
    "BOK_STATUS" TEXT NOT NULL DEFAULT 'confirmed',
    "BOK_BOOKED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "BOK_ATTENDED_AT" DATETIME,
    "BOK_CANCELLED_AT" DATETIME,
    "BOK_NOTES" TEXT,
    "BOK_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "BOK_UPDATED_AT" DATETIME NOT NULL,
    CONSTRAINT "MOV_BOOKING_BOK_TENANT_ID_fkey" FOREIGN KEY ("BOK_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MOV_BOOKING_BOK_MEMBER_ID_fkey" FOREIGN KEY ("BOK_MEMBER_ID") REFERENCES "MOV_MEMBER" ("MEM_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MOV_BOOKING_BOK_SESSION_INSTANCE_ID_fkey" FOREIGN KEY ("BOK_SESSION_INSTANCE_ID") REFERENCES "MOV_SESSION_INSTANCE" ("SIN_ID") ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO "MOV_BOOKING" SELECT * FROM "Booking" WHERE 1=0;
DROP TABLE IF EXISTS "Booking";

CREATE UNIQUE INDEX "MOV_BOOKING_BOK_MEMBER_ID_BOK_SESSION_INSTANCE_ID_key" ON "MOV_BOOKING"("BOK_MEMBER_ID", "BOK_SESSION_INSTANCE_ID");
CREATE INDEX "MOV_BOOKING_BOK_TENANT_ID_idx" ON "MOV_BOOKING"("BOK_TENANT_ID");
CREATE INDEX "MOV_BOOKING_BOK_MEMBER_ID_idx" ON "MOV_BOOKING"("BOK_MEMBER_ID");
CREATE INDEX "MOV_BOOKING_BOK_SESSION_INSTANCE_ID_idx" ON "MOV_BOOKING"("BOK_SESSION_INSTANCE_ID");
CREATE INDEX "MOV_BOOKING_BOK_STATUS_idx" ON "MOV_BOOKING"("BOK_STATUS");
CREATE INDEX "MOV_BOOKING_BOK_BOOKED_AT_idx" ON "MOV_BOOKING"("BOK_BOOKED_AT");

-- =============================================================================
-- MOVEMENT_EVENT TABLE: MovementEvent → PLP_MOVEMENT_EVENT with MVE_ prefix
-- Note: This is PLP_ domain (PulseLoop) not MOV_
-- =============================================================================

CREATE TABLE "PLP_MOVEMENT_EVENT" (
    "MVE_ID" TEXT NOT NULL PRIMARY KEY,
    "MVE_TENANT_ID" TEXT NOT NULL,
    "MVE_MEMBER_ID" TEXT NOT NULL,
    "MVE_SESSION_INSTANCE_ID" TEXT,
    "MVE_TYPE" TEXT NOT NULL,
    "MVE_METADATA" TEXT,
    "MVE_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PLP_MOVEMENT_EVENT_MVE_TENANT_ID_fkey" FOREIGN KEY ("MVE_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "PLP_MOVEMENT_EVENT_MVE_MEMBER_ID_fkey" FOREIGN KEY ("MVE_MEMBER_ID") REFERENCES "MOV_MEMBER" ("MEM_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "PLP_MOVEMENT_EVENT_MVE_SESSION_INSTANCE_ID_fkey" FOREIGN KEY ("MVE_SESSION_INSTANCE_ID") REFERENCES "MOV_SESSION_INSTANCE" ("SIN_ID") ON DELETE SET NULL ON UPDATE CASCADE
);

INSERT INTO "PLP_MOVEMENT_EVENT" SELECT * FROM "MovementEvent" WHERE 1=0;
DROP TABLE IF EXISTS "MovementEvent";

CREATE INDEX "PLP_MOVEMENT_EVENT_MVE_TENANT_ID_idx" ON "PLP_MOVEMENT_EVENT"("MVE_TENANT_ID");
CREATE INDEX "PLP_MOVEMENT_EVENT_MVE_MEMBER_ID_idx" ON "PLP_MOVEMENT_EVENT"("MVE_MEMBER_ID");
CREATE INDEX "PLP_MOVEMENT_EVENT_MVE_CREATED_AT_idx" ON "PLP_MOVEMENT_EVENT"("MVE_CREATED_AT");
CREATE INDEX "PLP_MOVEMENT_EVENT_MVE_TYPE_idx" ON "PLP_MOVEMENT_EVENT"("MVE_TYPE");
CREATE INDEX "PLP_MOVEMENT_EVENT_MVE_SESSION_INSTANCE_ID_idx" ON "PLP_MOVEMENT_EVENT"("MVE_SESSION_INSTANCE_ID");

-- =============================================================================
-- WAITLIST TABLE: Waitlist → MOV_WAITLIST with WAI_ prefix
-- =============================================================================

CREATE TABLE "MOV_WAITLIST" (
    "WAI_ID" TEXT NOT NULL PRIMARY KEY,
    "WAI_TENANT_ID" TEXT NOT NULL,
    "WAI_MEMBER_ID" TEXT NOT NULL,
    "WAI_SESSION_INSTANCE_ID" TEXT NOT NULL,
    "WAI_POSITION" INTEGER NOT NULL,
    "WAI_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "WAI_UPDATED_AT" DATETIME NOT NULL,
    CONSTRAINT "MOV_WAITLIST_WAI_TENANT_ID_fkey" FOREIGN KEY ("WAI_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MOV_WAITLIST_WAI_MEMBER_ID_fkey" FOREIGN KEY ("WAI_MEMBER_ID") REFERENCES "MOV_MEMBER" ("MEM_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MOV_WAITLIST_WAI_SESSION_INSTANCE_ID_fkey" FOREIGN KEY ("WAI_SESSION_INSTANCE_ID") REFERENCES "MOV_SESSION_INSTANCE" ("SIN_ID") ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO "MOV_WAITLIST" SELECT * FROM "Waitlist" WHERE 1=0;
DROP TABLE IF EXISTS "Waitlist";

CREATE UNIQUE INDEX "MOV_WAITLIST_WAI_MEMBER_ID_WAI_SESSION_INSTANCE_ID_key" ON "MOV_WAITLIST"("WAI_MEMBER_ID", "WAI_SESSION_INSTANCE_ID");
CREATE INDEX "MOV_WAITLIST_WAI_TENANT_ID_idx" ON "MOV_WAITLIST"("WAI_TENANT_ID");
CREATE INDEX "MOV_WAITLIST_WAI_MEMBER_ID_idx" ON "MOV_WAITLIST"("WAI_MEMBER_ID");
CREATE INDEX "MOV_WAITLIST_WAI_SESSION_INSTANCE_ID_idx" ON "MOV_WAITLIST"("WAI_SESSION_INSTANCE_ID");

-- =============================================================================
-- FAVORITE TABLE: Favorite → MOV_FAVORITE with FAV_ prefix
-- =============================================================================

CREATE TABLE "MOV_FAVORITE" (
    "FAV_ID" TEXT NOT NULL PRIMARY KEY,
    "FAV_TENANT_ID" TEXT NOT NULL,
    "FAV_MEMBER_ID" TEXT NOT NULL,
    "FAV_SESSION_TYPE_ID" TEXT NOT NULL,
    "FAV_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "MOV_FAVORITE_FAV_TENANT_ID_fkey" FOREIGN KEY ("FAV_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MOV_FAVORITE_FAV_MEMBER_ID_fkey" FOREIGN KEY ("FAV_MEMBER_ID") REFERENCES "MOV_MEMBER" ("MEM_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MOV_FAVORITE_FAV_SESSION_TYPE_ID_fkey" FOREIGN KEY ("FAV_SESSION_TYPE_ID") REFERENCES "MOV_SESSION_TYPE" ("STY_ID") ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO "MOV_FAVORITE" SELECT * FROM "Favorite" WHERE 1=0;
DROP TABLE IF EXISTS "Favorite";

CREATE UNIQUE INDEX "MOV_FAVORITE_FAV_MEMBER_ID_FAV_SESSION_TYPE_ID_key" ON "MOV_FAVORITE"("FAV_MEMBER_ID", "FAV_SESSION_TYPE_ID");
CREATE INDEX "MOV_FAVORITE_FAV_TENANT_ID_idx" ON "MOV_FAVORITE"("FAV_TENANT_ID");
CREATE INDEX "MOV_FAVORITE_FAV_MEMBER_ID_idx" ON "MOV_FAVORITE"("FAV_MEMBER_ID");
CREATE INDEX "MOV_FAVORITE_FAV_SESSION_TYPE_ID_idx" ON "MOV_FAVORITE"("FAV_SESSION_TYPE_ID");

PRAGMA foreign_keys=ON;
