-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_MOV_LOCATION" (
    "LOC_ID" TEXT NOT NULL PRIMARY KEY,
    "LOC_TENANT_ID" TEXT NOT NULL,
    "LOC_NAME" TEXT NOT NULL,
    "LOC_ADDRESS" TEXT,
    "LOC_STREET_NUMBER" TEXT,
    "LOC_STREET_NAME" TEXT,
    "LOC_CITY" TEXT,
    "LOC_COUNTY" TEXT,
    "LOC_PROVINCE" TEXT,
    "LOC_POSTAL_CODE" TEXT,
    "LOC_COUNTRY" TEXT,
    "LOC_LATITUDE" REAL,
    "LOC_LONGITUDE" REAL,
    "LOC_ELEVATION" REAL,
    "LOC_CAPACITY" INTEGER,
    "LOC_TYPE" TEXT NOT NULL DEFAULT 'indoor',
    "LOC_TIMEZONE" TEXT NOT NULL DEFAULT 'UTC',
    "LOC_REQUIRES_WEATHER" BOOLEAN NOT NULL DEFAULT false,
    "LOC_WEATHER_ALERT" BOOLEAN NOT NULL DEFAULT false,
    "LOC_CORPORATE_ID" TEXT,
    "LOC_BUILDING_NAME" TEXT,
    "LOC_FLOOR" TEXT,
    "LOC_ROOM_NUMBER" TEXT,
    "LOC_ACCESS_INSTRUCTIONS" TEXT,
    "LOC_IS_ACTIVE" BOOLEAN NOT NULL DEFAULT true,
    "LOC_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "LOC_UPDATED_AT" DATETIME NOT NULL,
    CONSTRAINT "MOV_LOCATION_LOC_TENANT_ID_fkey" FOREIGN KEY ("LOC_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_MOV_LOCATION" ("LOC_ADDRESS", "LOC_CAPACITY", "LOC_CREATED_AT", "LOC_ID", "LOC_IS_ACTIVE", "LOC_NAME", "LOC_TENANT_ID", "LOC_TIMEZONE", "LOC_UPDATED_AT") SELECT "LOC_ADDRESS", "LOC_CAPACITY", "LOC_CREATED_AT", "LOC_ID", "LOC_IS_ACTIVE", "LOC_NAME", "LOC_TENANT_ID", "LOC_TIMEZONE", "LOC_UPDATED_AT" FROM "MOV_LOCATION";
DROP TABLE "MOV_LOCATION";
ALTER TABLE "new_MOV_LOCATION" RENAME TO "MOV_LOCATION";
CREATE INDEX "MOV_LOCATION_LOC_TENANT_ID_idx" ON "MOV_LOCATION"("LOC_TENANT_ID");
CREATE INDEX "MOV_LOCATION_LOC_IS_ACTIVE_idx" ON "MOV_LOCATION"("LOC_IS_ACTIVE");
CREATE INDEX "MOV_LOCATION_LOC_COUNTRY_LOC_PROVINCE_LOC_CITY_idx" ON "MOV_LOCATION"("LOC_COUNTRY", "LOC_PROVINCE", "LOC_CITY");
CREATE INDEX "MOV_LOCATION_LOC_LATITUDE_LOC_LONGITUDE_idx" ON "MOV_LOCATION"("LOC_LATITUDE", "LOC_LONGITUDE");
CREATE INDEX "MOV_LOCATION_LOC_CORPORATE_ID_idx" ON "MOV_LOCATION"("LOC_CORPORATE_ID");
CREATE INDEX "MOV_LOCATION_LOC_TYPE_idx" ON "MOV_LOCATION"("LOC_TYPE");
CREATE UNIQUE INDEX "MOV_LOCATION_LOC_TENANT_ID_LOC_NAME_key" ON "MOV_LOCATION"("LOC_TENANT_ID", "LOC_NAME");
CREATE TABLE "new_MOV_SESSION_INSTANCE" (
    "SIN_ID" TEXT NOT NULL PRIMARY KEY,
    "SIN_TENANT_ID" TEXT NOT NULL,
    "SIN_SESSION_TYPE_ID" TEXT NOT NULL,
    "SIN_LOCATION_ID" TEXT NOT NULL,
    "SIN_START_TIME" DATETIME NOT NULL,
    "SIN_END_TIME" DATETIME NOT NULL,
    "SIN_CAPACITY" INTEGER,
    "SIN_STATUS" TEXT NOT NULL DEFAULT 'scheduled',
    "SIN_INSTRUCTOR" TEXT,
    "SIN_NOTES" TEXT,
    "SIN_WEATHER_CHECKED" BOOLEAN NOT NULL DEFAULT false,
    "SIN_WEATHER_SAFE" BOOLEAN,
    "SIN_WEATHER_DATA" JSONB,
    "SIN_WEATHER_CHECKED_AT" DATETIME,
    "SIN_WEATHER_ALERT_SENT" BOOLEAN NOT NULL DEFAULT false,
    "SIN_MEETING_POINT" TEXT,
    "SIN_ROUTE_DETAILS" JSONB,
    "SIN_ALTERNATIVE_VENUE" TEXT,
    "SIN_CORPORATE_ID" TEXT,
    "SIN_POINTS_AWARDED" INTEGER,
    "SIN_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "SIN_UPDATED_AT" DATETIME NOT NULL,
    CONSTRAINT "MOV_SESSION_INSTANCE_SIN_TENANT_ID_fkey" FOREIGN KEY ("SIN_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MOV_SESSION_INSTANCE_SIN_SESSION_TYPE_ID_fkey" FOREIGN KEY ("SIN_SESSION_TYPE_ID") REFERENCES "MOV_SESSION_TYPE" ("STY_ID") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "MOV_SESSION_INSTANCE_SIN_LOCATION_ID_fkey" FOREIGN KEY ("SIN_LOCATION_ID") REFERENCES "MOV_LOCATION" ("LOC_ID") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_MOV_SESSION_INSTANCE" ("SIN_CAPACITY", "SIN_CREATED_AT", "SIN_END_TIME", "SIN_ID", "SIN_INSTRUCTOR", "SIN_LOCATION_ID", "SIN_NOTES", "SIN_SESSION_TYPE_ID", "SIN_START_TIME", "SIN_STATUS", "SIN_TENANT_ID", "SIN_UPDATED_AT") SELECT "SIN_CAPACITY", "SIN_CREATED_AT", "SIN_END_TIME", "SIN_ID", "SIN_INSTRUCTOR", "SIN_LOCATION_ID", "SIN_NOTES", "SIN_SESSION_TYPE_ID", "SIN_START_TIME", "SIN_STATUS", "SIN_TENANT_ID", "SIN_UPDATED_AT" FROM "MOV_SESSION_INSTANCE";
DROP TABLE "MOV_SESSION_INSTANCE";
ALTER TABLE "new_MOV_SESSION_INSTANCE" RENAME TO "MOV_SESSION_INSTANCE";
CREATE INDEX "MOV_SESSION_INSTANCE_SIN_TENANT_ID_idx" ON "MOV_SESSION_INSTANCE"("SIN_TENANT_ID");
CREATE INDEX "MOV_SESSION_INSTANCE_SIN_START_TIME_idx" ON "MOV_SESSION_INSTANCE"("SIN_START_TIME");
CREATE INDEX "MOV_SESSION_INSTANCE_SIN_STATUS_idx" ON "MOV_SESSION_INSTANCE"("SIN_STATUS");
CREATE INDEX "MOV_SESSION_INSTANCE_SIN_SESSION_TYPE_ID_idx" ON "MOV_SESSION_INSTANCE"("SIN_SESSION_TYPE_ID");
CREATE INDEX "MOV_SESSION_INSTANCE_SIN_LOCATION_ID_idx" ON "MOV_SESSION_INSTANCE"("SIN_LOCATION_ID");
CREATE INDEX "MOV_SESSION_INSTANCE_SIN_WEATHER_SAFE_idx" ON "MOV_SESSION_INSTANCE"("SIN_WEATHER_SAFE");
CREATE INDEX "MOV_SESSION_INSTANCE_SIN_CORPORATE_ID_idx" ON "MOV_SESSION_INSTANCE"("SIN_CORPORATE_ID");
CREATE UNIQUE INDEX "MOV_SESSION_INSTANCE_SIN_LOCATION_ID_SIN_START_TIME_key" ON "MOV_SESSION_INSTANCE"("SIN_LOCATION_ID", "SIN_START_TIME");
CREATE TABLE "new_MOV_SESSION_TYPE" (
    "STY_ID" TEXT NOT NULL PRIMARY KEY,
    "STY_TENANT_ID" TEXT NOT NULL,
    "STY_NAME" TEXT NOT NULL,
    "STY_DESCRIPTION" TEXT,
    "STY_DURATION_MIN" INTEGER NOT NULL,
    "STY_CATEGORY" TEXT NOT NULL,
    "STY_MAX_CAPACITY" INTEGER,
    "STY_DIFFICULTY" TEXT NOT NULL DEFAULT 'intermediate',
    "STY_IS_OUTDOOR" BOOLEAN NOT NULL DEFAULT false,
    "STY_REQUIRES_WEATHER" BOOLEAN NOT NULL DEFAULT false,
    "STY_WEATHER_CONDITIONS" TEXT,
    "STY_TEMP_MIN" REAL,
    "STY_TEMP_MAX" REAL,
    "STY_EQUIPMENT" TEXT,
    "STY_FITNESS_LEVEL" TEXT,
    "STY_CORPORATE_APPROVED" BOOLEAN NOT NULL DEFAULT true,
    "STY_CREDIT_POINTS" INTEGER,
    "STY_IS_ACTIVE" BOOLEAN NOT NULL DEFAULT true,
    "STY_CREATED_AT" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "STY_UPDATED_AT" DATETIME NOT NULL,
    CONSTRAINT "MOV_SESSION_TYPE_STY_TENANT_ID_fkey" FOREIGN KEY ("STY_TENANT_ID") REFERENCES "MOV_TENANT" ("TEN_ID") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_MOV_SESSION_TYPE" ("STY_CATEGORY", "STY_CREATED_AT", "STY_DESCRIPTION", "STY_DIFFICULTY", "STY_DURATION_MIN", "STY_ID", "STY_IS_ACTIVE", "STY_MAX_CAPACITY", "STY_NAME", "STY_TENANT_ID", "STY_UPDATED_AT") SELECT "STY_CATEGORY", "STY_CREATED_AT", "STY_DESCRIPTION", "STY_DIFFICULTY", "STY_DURATION_MIN", "STY_ID", "STY_IS_ACTIVE", "STY_MAX_CAPACITY", "STY_NAME", "STY_TENANT_ID", "STY_UPDATED_AT" FROM "MOV_SESSION_TYPE";
DROP TABLE "MOV_SESSION_TYPE";
ALTER TABLE "new_MOV_SESSION_TYPE" RENAME TO "MOV_SESSION_TYPE";
CREATE INDEX "MOV_SESSION_TYPE_STY_TENANT_ID_idx" ON "MOV_SESSION_TYPE"("STY_TENANT_ID");
CREATE INDEX "MOV_SESSION_TYPE_STY_CATEGORY_idx" ON "MOV_SESSION_TYPE"("STY_CATEGORY");
CREATE INDEX "MOV_SESSION_TYPE_STY_IS_ACTIVE_idx" ON "MOV_SESSION_TYPE"("STY_IS_ACTIVE");
CREATE INDEX "MOV_SESSION_TYPE_STY_IS_OUTDOOR_idx" ON "MOV_SESSION_TYPE"("STY_IS_OUTDOOR");
CREATE INDEX "MOV_SESSION_TYPE_STY_CORPORATE_APPROVED_idx" ON "MOV_SESSION_TYPE"("STY_CORPORATE_APPROVED");
CREATE UNIQUE INDEX "MOV_SESSION_TYPE_STY_TENANT_ID_STY_NAME_key" ON "MOV_SESSION_TYPE"("STY_TENANT_ID", "STY_NAME");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
